### PR TITLE
Restore allowing CORS, but only in debug mode

### PR DESCRIPTION
**Pull request by lmanul**
...and print an explicit warning.

### CODE REVIEW

**Comment by lmanul** [comment]
@DavidMStraub @FiloSottile

**Comment by DavidMStraub** [comment]
Great idea. This should solve the problem discussed in #5 without compromising security in production.

**Comment by ryneeverett** [comment]
Surely there's no reason to open it up so much. You can limit the origins by host and port.

**Comment by DavidMStraub** [comment]
Good point @ryneeverett, maybe I was a bit too quick merging it, but at least the development setup works again now...

**Comment by lmanul** [comment]
Thank you for merging! I can definitely work on restricting this a little more, but I think as long as anyone running this in debug mode is aware of the risk, I think we're clear of the main concern here.

**Pull request merged**
