### PR TITLE
Replaced deprecated import for safe_join (now: werkzeug.security)

### PR DESCRIPTION
**Pull request by cookie4701**

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Thanks for this PR!

Can you please add the link to the documentation in flask that this is deprecated?

Also, can you please check what the minimum version of flask and werkzeug are that are required for these imports to work and make sure we have those minimum versions required in setup.py?

**Comment by DavidMStraub** [comment]
Ok, saw the ImportError in https://github.com/DavidMStraub/netviel-docker/issues/1 only now. But we have to make sure the right flask version is required.

**Comment by lmanul** [comment]
Stupid question (sorry): what is the downside of using os.path.join instead? I saw the same import error today for the first time, and just used os.path.join instead.

**Comment by DavidMStraub** [comment]
From the docs:

> Safely join zero or more untrusted path components to a base directory to avoid escaping the base directory.

**Comment by DavidMStraub** [comment]
Superseded by #17.

**Pull request closed without merging**
