### PR TITLE
Add a simple 'developers' page and a link from the README

### PR DESCRIPTION
**Pull request by lmanul**
@DavidMStraub -- this fixes issue #5

### CODE REVIEW

**Comment by lmanul** [comment]
Ping @DavidMStraub ? :-)

**Comment by DavidMStraub** [comment]
Thanks for the PR!

Just a little bit of patience, I don't have time every day to look into PRs but will do so very soon.

**Comment by lmanul** [comment]
Oooh, sorry for giving you any time pressure, I thought you might just have missed it. Take all the time you need of course :-)

**Comment by DavidMStraub** [comment]
Thanks again & sorry for the delay!

Looks very good, only a small change: `cd netviel && python3 setup.py build` should be replaced by `cd netviel && python3 -m pip install -e . --user `, and then this pip install should be removed under "running a test server".

**Comment by lmanul** [comment]
@DavidMStraub Done, thanks!

**Pull request merged**
